services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recipe_site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/.env:/backend/.env
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"       # React (через nginx) будет на 3000 (80 внутри контейнера)
    env_file:
      - ./frontend/.env

  nginx:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:


        
      

      



