# Generated by Django 5.2.1 on 2025-05-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_customuser_options_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('description', models.TextField(max_length=600, verbose_name='Описание шага')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_steps', verbose_name='Фото шага')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='backend_api.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Шаг рецепта',
                'verbose_name_plural': 'Шагы рецепта',
                'ordering': ['step_number'],
            },
        ),
    ]
