# Generated by Django 5.2.1 on 2025-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_recipestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images', verbose_name='Фото рецепта'),
        ),
    ]
