# Generated by Django 5.2.1 on 2025-06-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='craeted',
            new_name='created',
        ),
    ]
