# Generated by Django 5.2.1 on 2025-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_rename_craeted_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['recipe'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
